# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Code quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  QA-check:
    name: Code quality assurance

    runs-on: self-hosted

    container: 
      image: python:3.12

    steps:
    - uses: actions/checkout@v4
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "src/"
        use-mypy: true
        use-black: true
        use-pylint: false
        use-pycodestyle: false
        use-flake8: false
        use-isort: false
        extra-mypy-options: "--strict --pretty"



