# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m venv .venv 
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install mypy
    - name: Check 
      run: |
        source .venv/bin/activate
        mypy --strict --pretty src/
